IVT computation app
LBL-EESA/TECA pull request #486
Opened 2020-10-13 21:14 UTC by elbashandy

Resolves #391

2020-10-15 19:42 UTC, burlen requested changes
Looking good but I see a few things that should be changed.

2020-10-15 19:42 UTC, burlen commented on apps/CMakeLists.txt
> +teca_add_app(teca_ivt_computation LIBS ${teca_app_link}
let's change the name to `teca_integrated_vapor_transport`

2020-10-15 19:42 UTC, burlen commented on apps/teca_ivt_computation.cpp
> +        ("point_arrays", value<std::vector<std::string>>()->multitoken(), "list of point centered arrays to write")
not needed

2020-10-16 16:04 UTC, elbashandy commented
@burlen Thanks for reviewing this. I think I covered all the required changes. Please give it a look when you have a chance.

2020-10-16 16:25 UTC, elbashandy commented on apps/teca_cartesian_mesh_diff.cpp
> +    std::string test_file = argv[2];
Yes I must have made a mistake while rebasing. Just checked, everything looks in place.

2020-10-19 16:11 UTC, burlen requested changes
a few changes to be made

2020-10-28 00:31 UTC, burlen commented on test/apps/test_integrated_vapor_transport_app.sh
> +    "test_ivt_computation_app_output.*\.nc"
confirmed. teca_cartesian_mesh diff doesn't use the index executive as a result an empty request is always made, hence step 0 is always requested and no arrays are being compared. this also explains why it didn't matter which order the reference and test datasets were passed on the command line. Added an issue for this #498

2020-10-29 16:00 UTC, burlen approved these changes
all set, but depends on #499. hold off until that is merged

2020-11-06 01:08 UTC, merged